export const Types = {
    ALL_MONEYS: 'ALL_MONEYS',
    ADD_MONEYS: 'ADD_MONEYS',
    UPDATE_MONEYS: 'UPDATE_MONEYS',
    DELETE_MONEYS: 'DELETE_MONEYS',
    ADD_MONEY_FILTER: 'ADD_MONEY_FILTER',
    GET_CHART_DATA: 'GET_CHART_DATA',
}
