export const Types = {
    ALL_MEMBERS: 'ALL_MEMBERS',
    ADD_MEMBERS: 'ADD_MEMBERS',
    UPDATE_MEMBERS: 'UPDATE_MEMBERS',
    DELETE_MEMBERS: 'DELETE_MEMBERS',
    ADD_MEMBER_FILTER: 'ADD_MEMBER_FILTER',
    GET_CHART_DATA: 'GET_CHART_DATA',
}
