export const Types = {
    ALL_RECEIVED_ORDERS: 'ALL_RECEIVED_ORDERS',
    ADD_RECEIVED_ORDERS: 'ADD_RECEIVED_ORDERS',
    UPDATE_RECEIVED_ORDERS: 'UPDATE_RECEIVED_ORDERS',
    DELETE_RECEIVED_ORDERS: 'DELETE_RECEIVED_ORDERS',
}
