export const Types = {
    ALL_EXPENSES: 'ALL_EXPENSES',
    ADD_EXPENSES: 'ADD_EXPENSES',
    UPDATE_EXPENSES: 'UPDATE_EXPENSES',
    DELETE_EXPENSES: 'DELETE_EXPENSES',
    ADD_EXPENSES_FILTER: 'ADD_EXPENSES_FILTER',
    GET_EXPENSES_CHART: 'GET_EXPENSES_CHART',
}
