export const Types = {
    ALL_ORDER_RETURNS: 'ALL_ORDER_RETURNS',
    ADD_ORDER_RETURNS: 'ADD_ORDER_RETURNS',
    UPDATE_ORDER_RETURNS: 'UPDATE_ORDER_RETURNS',
    DELETE_ORDER_RETURNS: 'DELETE_ORDER_RETURNS',
}
