export const Types = {
    COMMON_SUPPLIERS: 'COMMON_SUPPLIERS',
    COMMON_PRODUCTS: 'COMMON_PRODUCTS',
    COMMON_EMPLOYEES: 'COMMON_EMPLOYEES',
    COMMON_DISPATCH_ORDERS: 'COMMON_DISPATCH_ORDERS',
    COMMON_TRUCKS: 'COMMON_TRUCKS',
}
