export const Types = {
    ALL_CASH_UPS: 'ALL_CASH_UPS',
    ADD_CASH_UPS: 'ADD_CASH_UPS',
    UPDATE_CASH_UPS: 'UPDATE_CASH_UPS',
    DELETE_CASH_UPS: 'DELETE_CASH_UPS',
    ADD_CASHUP_FILTER: 'ADD_CASHUP_FILTER',
    GET_CHART_DATA: 'GET_CHART_DATA',
}
