export const Types = {
    ALL_RECORDS: 'ALL_RECORDS',
    ADD_RECORDS: 'ADD_RECORDS',
    SINGLE_RECORD: 'SINGLE_RECORD',
    UPDATE_RECORDS: 'UPDATE_RECORDS',
    DELETE_RECORDS: 'DELETE_RECORDS',
    ADD_RECORD_FILTER: 'ADD_RECORD_FILTER',
    GET_CHART_DATA: 'GET_CHART_DATA',
}
