export const Types = {
    ALL_BUSINESSES: 'ALL_BUSINESSES',
    ADD_BUSINESS: 'ADD_BUSINESS',
    UPDATE_BUSINESS: 'UPDATE_BUSINESS',
    GET_BUSINESS_DETAIL: 'GET_BUSINESS_DETAIL',
    DELETE_BUSINESS: 'DELETE_BUSINESS',
}
