export const Types = {
  GET_DISPATCH_ORDERS: 'GET_DISPATCH_ORDERS',
  GET_DISPATCH_ORDER: 'GET_DISPATCH_ORDER',
  ADD_DISPATCH_ORDER: 'ADD_DISPATCH_ORDER',
  REMOVE_DISPATCH_ORDER: 'REMOVE_DISPATCH_ORDER',
  UPDATE_DISPATCH_ORDER: 'UPDATE_DISPATCH_ORDER',
}
